### PR TITLE
Move CurrentRoundRow to Human main page

### PR DESCRIPTION
**Pull request by alfakini**

### CODE REVIEW

**Comment by alfakini** [comment]
[[COMPONENT] Integrate CurrentRoundRow to Human/Home page](https://trello.com/c/ymk4R0MU/208-component-integrate-currentroundrow-to-human-home-page)

**Comment by alfakini** [comment]
[[COMPONENT] Integrate CurrentRoundRow to Human/Home page](https://trello.com/c/ymk4R0MU/208-component-integrate-currentroundrow-to-human-home-page)

**Comment by alfakini** [comment]
[[COMPONENT] Integrate CurrentRoundRow to Human/Home page](https://trello.com/c/ymk4R0MU/208-component-integrate-currentroundrow-to-human-home-page)

**Comment by alfakini** [comment]
[[COMPONENT] Integrate CurrentRoundRow to Human/Home page](https://trello.com/c/ymk4R0MU/208-component-integrate-currentroundrow-to-human-home-page)

**Comment by alfakini** [comment]
[[COMPONENT] Integrate CurrentRoundRow to Human/Home page](https://trello.com/c/ymk4R0MU/208-component-integrate-currentroundrow-to-human-home-page)

**Review by murilooon — APPROVED** [review]

**Pull request merged**
